#!/bin/sh
# Rebuilds vice/src/restapi_sidcrt.h and vice/src/restapi_muscrt.h, the player
# cartridges runners:sidplay starts, from the sources in restapi-sidcrt/.
#
# The sources are Wilfred Bos' "Ultimate SID Player" from the 1541-Ultimate
# firmware at tag 1.1.0 (Commodore's release, commit 7b628eb1), with changes on
# top: f0c51d11 from the firmware's master (in 3.15a, not in 1.1.0), "Fix
# installing extra player in some scenario when there is enough space after
# load end address", and the player commits of GideonZ/1541ultimate#949 up to
# cdb9c23f: the info screen as a table under a yellow heading row, ADDR,
# MODEL, VIDEO and IRQ; the NEEDS lines the header asks for, then the FOUND
# lines measured at every address the tune names; UNKNOWN where no SID, or
# only a mirror of the one at $D400, answers; an UltiSID set to 8580 told from
# a 6581 by its combined waveforms; SID #1's model for a SID the header leaves
# open, as the SID file format defines it; and VBI, CIA or RSID for the
# song's interrupt. The only difference left from that firmware's players is
# the title line, which keeps 1.1.0's wording.
#
# #949 also moves the plain-letter conversion of title, author and released
# out of the player into the code that hands it the header; here that is
# restapi_sidplay.c, with the firmware's table.
#
# The MUS player cartridge (muscrt.asm) is built from the same sources, and
# musplayer.asm is COMPUTE!'s Sidplayer by Craig Chamberlain and Harry Bratt as
# the firmware ships it, a byte listing that the device copies to $E000.
#
# They are assembled the way that firmware's Makefile does it, with the 64tass
# it ships (tools/64tass, V1.53.1515): newer releases reject the source. That
# binary is x86-64 Linux, so it runs in Docker here.
#
# Needs docker, curl and python3. The results must match the checksums below; a
# different one means the sources or the assembler changed.
set -e
here=$(cd "$(dirname "$0")" && pwd)
expected=ca7a76c3c839cdec35e073669b13ddc89635286c923b57646ec4652fc086480b
expected_mus=7a70216fa7f1ddb17a889909b8acc96f3de3d47889c504bf9d0975e112e1610c
expected_musplayer=92bb91eb94556efa404a5af03104cc387851c7c7080e3238bba477b50db66999
tool=https://raw.githubusercontent.com/enver-haase/1541ultimate/1.1.0/tools/64tass/64tass

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cp -R "$here/restapi-sidcrt/." "$work/"
curl -fsSL -o "$work/64tass" "$tool"
chmod +x "$work/64tass"

docker run --rm --platform linux/amd64 -v "$work:/w" -w /w ubuntu:24.04 sh -c '
  set -e
  mkdir -p target
  ./64tass --nostart -o target/player.bin player/player.asm
  ./64tass --nostart -D INCLUDE_RUNSTOP=0 -o target/advancedplayer.bin player/advanced/advancedplayer.asm
  ./64tass -o target/sidcrt.bin -b sidcrt.asm
  ./64tass -o target/muscrt.bin -b muscrt.asm
  ./64tass --nostart -o target/musplayer.bin musplayer.asm
'

python3 - "$work/target" "$here/vice/src" "$expected" "$expected_mus" "$expected_musplayer" <<'PYEOF'
import hashlib, sys
target, src, want_sid, want_mus, want_player = sys.argv[1:6]

SOURCES = (" *  firmware's tag 1.1.0 (commit 7b628eb1) plus commit f0c51d11 and the player\n"
           " *  commits of GideonZ/1541ultimate#949 up to cdb9c23f, as restapi-sidcrt.sh\n"
           " *  describes, with the firmware's own 64tass V1.53.1515.")


def load(name, want):
    data = open('%s/%s' % (target, name), 'rb').read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != want:
        sys.exit('%s has sha256 %s, expected %s' % (name, digest, want))
    return data, digest


def array(name, data):
    lines = []
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join('0x%02x' % b for b in data[i:i + 16]) + ',')
    return 'static const unsigned char %s[%d] = {\n%s\n};\n' % (name, len(data), '\n'.join(lines))


sid, sid_digest = load('sidcrt.bin', want_sid)
mus, mus_digest = load('muscrt.bin', want_mus)
player, player_digest = load('musplayer.bin', want_player)

open('%s/restapi_sidcrt.h' % src, 'w').write('''/** \\file   restapi_sidcrt.h
 *  \\brief  The SID player cartridge of the 1541-Ultimate firmware
 *
 *  Generated by restapi-sidcrt.sh from restapi-sidcrt/, do not edit.
 *
 *  "Ultimate SID Player V2.0d", Copyright (c) 2009-2023 Wilfred Bos / Gideon
 *  Zweijtzer, part of the 1541-Ultimate firmware and licensed with it under
 *  the GNU General Public License version 3. Assembled from the sources at the
%s
 *
 *  %d bytes, sha256 %s
 */

#ifndef VICE_RESTAPI_SIDCRT_H
#define VICE_RESTAPI_SIDCRT_H

%s
#endif
''' % (SOURCES, len(sid), sid_digest, array('restapi_sidcrt', sid)))
print('wrote restapi_sidcrt.h, %d bytes, sha256 %s' % (len(sid), sid_digest))

open('%s/restapi_muscrt.h' % src, 'w').write('''/** \\file   restapi_muscrt.h
 *  \\brief  The MUS player cartridge of the 1541-Ultimate firmware, and the
 *          COMPUTE!'s Sidplayer it plays the music with
 *
 *  Generated by restapi-sidcrt.sh from restapi-sidcrt/, do not edit.
 *
 *  The cartridge is the "Ultimate SID Player" built for Compute's Sidplayer
 *  data, Copyright (c) 2009-2023 Wilfred Bos / Gideon Zweijtzer; the player the
 *  device copies to $E000 is COMPUTE!'s Sidplayer by Craig Chamberlain and
 *  Harry Bratt, as the firmware ships it. Both are part of the 1541-Ultimate
 *  firmware and licensed with it under the GNU General Public License
 *  version 3. Assembled from the sources at the
%s
 *
 *  muscrt.bin %d bytes, sha256 %s
 *  musplayer.bin %d bytes, sha256 %s
 */

#ifndef VICE_RESTAPI_MUSCRT_H
#define VICE_RESTAPI_MUSCRT_H

%s
%s
#endif
''' % (SOURCES, len(mus), mus_digest, len(player), player_digest,
       array('restapi_muscrt', mus), array('restapi_musplayer', player)))
print('wrote restapi_muscrt.h, muscrt.bin %d bytes sha256 %s, musplayer.bin %d bytes sha256 %s'
      % (len(mus), mus_digest, len(player), player_digest))
PYEOF
