#!/bin/sh
# Rebuilds vice/src/restapi_sidcrt.h, the SID player cartridge runners:sidplay
# starts, from the sources in restapi-sidcrt/.
#
# The sources are Wilfred Bos' "Ultimate SID Player" from the 1541-Ultimate
# firmware at tag 1.1.0 (Commodore's release, commit 7b628eb1), with changes on
# top: f0c51d11 from the firmware's master (in 3.15a, not in 1.1.0), "Fix
# installing extra player in some scenario when there is enough space after
# load end address"; e84e1560 from GideonZ/1541ultimate#949, a SYSTEM line with
# the detected model for every SID the tune uses; and beea28f2, also from #949,
# which makes the SID #2 line show SID #1's model when the header leaves its
# model open, as the SID file format defines it: 1.1.0 meant to, and did for
# the third SID, but a missing flags mask made the second show UNKNOWN; and
# 610b191b, also from #949, which labels the measured lines FOUND and the
# requested ones WANT, numbered for more than one SID, with an empty line
# between the two. The only difference left from that firmware's player is
# the title line, which keeps 1.1.0's wording.
# They are assembled the way that firmware's Makefile does it, with the 64tass
# it ships (tools/64tass, V1.53.1515): newer releases reject the source. That
# binary is x86-64 Linux, so it runs in Docker here.
#
# Needs docker, curl and python3. The result must match the checksum below; a
# different one means the sources or the assembler changed.
set -e
here=$(cd "$(dirname "$0")" && pwd)
expected=4a905e298a621fcddc4e747a55fa98897ee42bdf6736c105567cf06cd8fb745a
tool=https://raw.githubusercontent.com/enver-haase/1541ultimate/1.1.0/tools/64tass/64tass

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cp -R "$here/restapi-sidcrt/." "$work/"
curl -fsSL -o "$work/64tass" "$tool"
chmod +x "$work/64tass"

docker run --rm --platform linux/amd64 -v "$work:/w" -w /w ubuntu:24.04 sh -c '
  set -e
  mkdir -p target
  ./64tass --nostart -o target/player.bin player/player.asm
  ./64tass --nostart -D INCLUDE_RUNSTOP=0 -o target/advancedplayer.bin player/advanced/advancedplayer.asm
  ./64tass -o target/sidcrt.bin -b sidcrt.asm
'

python3 - "$work/target/sidcrt.bin" "$here/vice/src/restapi_sidcrt.h" "$expected" <<'EOF'
import hashlib, sys
data = open(sys.argv[1], 'rb').read()
digest = hashlib.sha256(data).hexdigest()
if digest != sys.argv[3]:
    sys.exit('sidcrt.bin has sha256 %s, expected %s' % (digest, sys.argv[3]))
lines = []
for i in range(0, len(data), 16):
    lines.append('    ' + ', '.join('0x%02x' % b for b in data[i:i + 16]) + ',')
open(sys.argv[2], 'w').write('''/** \\file   restapi_sidcrt.h
 *  \\brief  The SID player cartridge of the 1541-Ultimate firmware
 *
 *  Generated by restapi-sidcrt.sh from restapi-sidcrt/, do not edit.
 *
 *  "Ultimate SID Player V2.0d", Copyright (c) 2009-2023 Wilfred Bos / Gideon
 *  Zweijtzer, part of the 1541-Ultimate firmware and licensed with it under
 *  the GNU General Public License version 3. Assembled from the sources at the
 *  firmware's tag 1.1.0 (commit 7b628eb1) plus commits f0c51d11, e84e1560,
 *  beea28f2 and 610b191b, as restapi-sidcrt.sh describes, with the firmware's own 64tass
 *  V1.53.1515.
 *
 *  %d bytes, sha256 %s
 */

#ifndef VICE_RESTAPI_SIDCRT_H
#define VICE_RESTAPI_SIDCRT_H

static const unsigned char restapi_sidcrt[%d] = {
%s
};

#endif
''' % (len(data), digest, len(data), '\n'.join(lines)))
print('wrote %s, %d bytes, sha256 %s' % (sys.argv[2], len(data), digest))
EOF
